name: RickyRomanxxx
favicon: null
layout_spectrum: 0.870927263982594
typography_spectrum: 0.3896886867005378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6902194190770388
  lightness: 0.508577908622101
  saturation: 0.2641154262237251
  rhythmicContrast: 0.5659460376482457
purpose: []
